### ISSUE TITLE
"Module file built by older version of compiler"

### ISSUE THREAD

**Issue by drnic** [brownleej/tailor#93]
![image](https://cloud.githubusercontent.com/assets/108/11600698/5562c5fa-9a83-11e5-95f0-47008453266f.png)

How do I "rebuild Tailor and try again"?

I am on XCode 7.1.1

**Comment by zuziakaxel** [comment]
Hi, just had same issue. I downloaded main Taylor project and compiled it. Then simply moved builded `Taylor.framework` to `/Libraries/Frameworks/`. ⭐️

**Comment by brownleej** [comment]
Sorry, all my efforts since December have been focused on the Linux port of Tailor. I just merged that into the master branch, and I'll get working on a Swift 2.2 build of Tailor for Mac this week.

**Comment by brownleej** [comment]
I've pushed out new releases of [Tailor](https://tailorframe.work/s/Tailor-v201mpkg.zip) and [TailorMysql](https://tailorframe.work/s/TailorMysql-v201framework.zip) that are built against Xcode 7.2.1 and Swift 2.1. Work on Swift 2.2 support is underway, but it won't make it into an official release until Swift 2.2 is out of beta.
